---
include:
  - ./zabbix-docker/docker-compose_v3_alpine_pgsql_latest.yaml
services:
  ts-zabbix-server:
    image: tailscale/tailscale:latest
    container_name: ts-zabbix-server
    hostname: zabbix
    environment:
      - TS_AUTHKEY=${TAILSCALE_OAUTH_KEY}
      - TS_EXTRA_ARGS=--advertise-tags=${TAILSCALE_TAGS}
      - TS_SERVE_CONFIG=/config/zabbix-server.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ts-zabbix-server-state:/var/lib/tailscale
      - ${PWD}/ts-zabbix-server/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  
volumes:
  ts-kuma-state:
    driver: local
  ts-zabbix-server-state:
    driver: local

