---
version: "3.7"
services:
  ts-wordpress:
    image: tailscale/tailscale:latest
    container_name: ts-wordpress
    hostname: wordpress-asb
    environment:
      - TS_AUTHKEY=${TAILSCALE_OAUTH_KEY}
      - TS_EXTRA_ARGS=--advertise-tags=${TAILSCALE_TAGS}
      - TS_SERVE_CONFIG=/config/wordpress.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ts-wordpress-state:/var/lib/tailscale
      - ${PWD}/ts-wordpress/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress-files:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  ts-wordpress-state:
    driver: local
  kuma-data:
    driver: local
  wordpress-files:
    driver: local
  db-data:
    driver: local
